# Secret Scanning Configuration
# This file configures which files should be ignored by GitHub Secret Scanning

# Ignore template files with placeholders
paths-ignore:
  - "**/*.template"
  - "**/*template*"
  - "mcp-servers.json.template"
  - "standards/zshrc.analysis.md"  # Contains example patterns, not real secrets

